version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/todo"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      app-network:
        aliases:
          - database
          - postgres

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge